/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica_3;

import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author isaac
 */
public class SalaSelector extends javax.swing.JFrame {
    private DatagramSocket socket;
    private String usuario;
    private DefaultListModel<String> modeloSalas = new DefaultListModel<>();
    private boolean escuchando = true; // Bandera para controlar el hilo


    /**
     * Creates new form SalaSelector
     */
    public SalaSelector(String usuario, DatagramSocket socket) {
        initComponents();
        this.usuario = usuario;
        this.socket = socket;
        lstSalas.setModel(modeloSalas);
        
        // 1. INICIAMOS EL HILO DE ESCUCHA AQUÍ
        iniciarListener();
        
        // 2. PEDIMOS LAS SALAS AL INICIAR
        actualizarSalas();
    }
    
    // Hilo que siempre está atento a lo que dice el servidor
    private void iniciarListener() {
        Thread hilo = new Thread(() -> {
            while (escuchando) {
                try {
                    byte[] buffer = new byte[1024];
                    DatagramPacket paquete = new DatagramPacket(buffer, buffer.length);
                    socket.receive(paquete); // Aquí se queda esperando sin congelar la ventana

                    String respuesta = new String(paquete.getData(), 0, paquete.getLength());
                    procesarMensaje(respuesta);

                } catch (Exception e) {
                    if(escuchando) System.out.println("Error en listener selector: " + e.getMessage());
                }
            }
        });
        hilo.start();
    }

    // Analiza qué llegó del servidor
    private void procesarMensaje(String xml) {
    if (xml.contains("<salas>")) {
        // ENVOLVER ESTO PARA PROTEGER LA GUI
        javax.swing.SwingUtilities.invokeLater(() -> {
            modeloSalas.clear(); 
            int pos = 0;
            while (true) {
                int ini = xml.indexOf("<sala>", pos);
                int fin = xml.indexOf("</sala>", pos);
                if (ini == -1 || fin == -1) break;
                String nombre = xml.substring(ini + 6, fin);
                modeloSalas.addElement(nombre);
                pos = fin + 7;
            }
        });
    }
}

    
    // =======================
    // MÉTODO PARA ENVIAR XML
    // =======================
    private void enviar(String mensaje) {
        try {
            byte[] buffer = mensaje.getBytes();
            DatagramPacket paquete = new DatagramPacket(
                    buffer, buffer.length,
                    InetAddress.getByName("127.0.0.1"),
                    8000 
            );
            socket.send(paquete);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al enviar: " + e.getMessage());
        }
    }
    
    // =======================
    // SOLICITAR LISTA DE SALAS
    // =======================
    private void actualizarSalas() {
        // Ya no recibimos aquí, solo pedimos
        enviar("<getsalas/>");
    }
    
    // =======================
    // UNIRSE A UNA SALA
    // =======================
    private void entrarSala() {
        String sala = lstSalas.getSelectedValue();
        if (sala == null) {
            JOptionPane.showMessageDialog(this, "Selecciona una sala.");
            return;
        }

        // 1. Detenemos la escucha lógica
        escuchando = false; 

        // 2. MATAMOS EL SOCKET VIEJO
        // Esto provocará una excepción en el hilo de SalaSelector y lo obligará a detenerse
        socket.close(); 

        try {
            // 3. Creamos un NUEVO socket limpio para el chat
            DatagramSocket nuevoSocket = new DatagramSocket();

            // 4. Abrimos el chat con el nuevo socket
            ChatSala chat = new ChatSala(usuario, sala, nuevoSocket);
            chat.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void crearSala() {
        String nombre = JOptionPane.showInputDialog(this, "Nombre de la sala nueva:");

        if (nombre == null || nombre.trim().isEmpty()) {
            return;
        }

        enviar("<crearsala><nombre>" + nombre + "</nombre></crearsala>");
        actualizarSalas();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSalas = new javax.swing.JList<>();
        btnEntrar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Salas disponibles");

        jScrollPane1.setViewportView(lstSalas);

        btnEntrar.setText("Entrar a sala");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear sala");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEntrar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar)
                            .addComponent(btnCrear))))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnEntrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
            entrarSala();   
            
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        crearSala();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        actualizarSalas();
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       throw new RuntimeException("No ejecutes SalaSelector directamente.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstSalas;
    // End of variables declaration//GEN-END:variables
}
